[package]
name = "byo-block-on"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"

[dependencies]
async-task = "1.3.0"
crossbeam = "0.7.3"
futures = "0.3.1"
pin-utils = "0.1.0-alpha.4"
